### ISSUE TITLE
Fetching user-specific credentials returns an error.

### ISSUE THREAD

**Issue by jelmersnoeck** [manifoldco/kubernetes-credentials#25]
When trying to fetch credentials linked to a user (not a team), the secrets don't get populated.

Configuration:

```yaml
apiVersion: manifold.co/v1
kind: Project
metadata:
  name: application-secrets
spec:
  project: kubernetes-application
```

This gives us the following error from the credentials-controller:

```
2018/08/14 15:06:45 Error getting the credentials:invalid character '<' looking for beginning of value
```

When switching this to a team API Token and Team resource (after transferring the resources), the secrets get populated.

```yaml
apiVersion: manifold.co/v1
kind: Project
metadata:
  name: application-secrets
spec:
  team: my-team
  project: kubernetes-application
```
